services:
  spark-quality-check:
    container_name: spark-quality-orders
    build: .
    command: >
      spark-submit
      --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.2
      --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.my_catalog.type=hadoop
      --conf spark.sql.catalog.my_catalog.warehouse=s3a://warehouse
      --conf spark.hadoop.fs.s3a.access.key=minioadmin
      --conf spark.hadoop.fs.s3a.secret.key=minioadmin
      --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
      --conf spark.hadoop.fs.s3a.path.style.access=true
      orders_quality_check.py
    networks:
      - data-net

  spark-quality-complaints:
    container_name: spark-quality-complaints
    build: .
    command: >
      spark-submit
      --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.2
      --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.my_catalog.type=hadoop
      --conf spark.sql.catalog.my_catalog.warehouse=s3a://warehouse
      --conf spark.hadoop.fs.s3a.access.key=minioadmin
      --conf spark.hadoop.fs.s3a.secret.key=minioadmin
      --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
      --conf spark.hadoop.fs.s3a.path.style.access=true
      complaints_quality_check.py
    networks:
      - data-net

  spark-quality-weather:
    container_name: spark-quality-weather
    build: .
    command: >
      spark-submit
      --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.2
      --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.my_catalog.type=hadoop
      --conf spark.sql.catalog.my_catalog.warehouse=s3a://warehouse
      --conf spark.hadoop.fs.s3a.access.key=minioadmin
      --conf spark.hadoop.fs.s3a.secret.key=minioadmin
      --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
      --conf spark.hadoop.fs.s3a.path.style.access=true
      weather_quality_check.py
    networks:
      - data-net

  spark-quality-deliveries:
    container_name: spark-quality-deliveries
    build: .
    command: >
      spark-submit
      --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.2
      --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.my_catalog.type=hadoop
      --conf spark.sql.catalog.my_catalog.warehouse=s3a://warehouse
      --conf spark.hadoop.fs.s3a.access.key=minioadmin
      --conf spark.hadoop.fs.s3a.secret.key=minioadmin
      --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
      --conf spark.hadoop.fs.s3a.path.style.access=true
      deliveries_quality_check.py
    networks:
      - data-net

  spark-quality-dim-time:
    container_name: spark-quality-dim-time
    build: .
    command: >
      spark-submit
      --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.2
      --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.my_catalog.type=hadoop
      --conf spark.sql.catalog.my_catalog.warehouse=s3a://warehouse
      --conf spark.hadoop.fs.s3a.access.key=minioadmin
      --conf spark.hadoop.fs.s3a.secret.key=minioadmin
      --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
      --conf spark.hadoop.fs.s3a.path.style.access=true
      dim_time_quality_check.py
    networks:
      - data-net

  spark-quality-dim-store:
    container_name: spark-quality-dim-store
    build: .
    command: >
      spark-submit
      --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.2
      --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.my_catalog.type=hadoop
      --conf spark.sql.catalog.my_catalog.warehouse=s3a://warehouse
      --conf spark.hadoop.fs.s3a.access.key=minioadmin
      --conf spark.hadoop.fs.s3a.secret.key=minioadmin
      --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
      --conf spark.hadoop.fs.s3a.path.style.access=true
      dim_store_quality_check.py
    networks:
      - data-net


networks:
  data-net:
    external: true
