services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # API (S3)
      - "9001:9001"  # Console (UI)
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/bronze;
      mc mb -p local/silver;
      mc mb -p local/gold;
      mc mb -p local/warehouse;
      exit 0;
      "

volumes:
  minio_data:
